services:
  - type: web
    name: SistemaWebParroquia-frontend
    env: static
    rootDir: frontend
    buildCommand: "npm install"
    startCommand: "npm start"
    plan: free
    region: oregon
    
  - type: web
    name: SistemaWebParroquia-backend
    env: python
    rootDir: backend
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn backend.wsgi:application --bind 0.0.0.0:$PORT"
    plan: free
    region: oregon
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: parroquia-db
          property: connectionString
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com,localhost,127.0.0.1"

  - type: redis
    name: parroquia-redis
    plan: free
    region: oregon
    maxmemoryPolicy: noeviction
    
  - type: postgres
    name: parroquia-db
    plan: free
    region: oregon
