# Generated by Django 5.0.2 on 2025-03-16 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Confirmacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_confirmacion', models.DateField()),
                ('nombre_confirmante', models.CharField(max_length=200)),
                ('fecha_nacimiento', models.DateField()),
                ('nombre_padre', models.CharField(blank=True, max_length=200)),
                ('nombre_madre', models.CharField(blank=True, max_length=200)),
                ('padrino', models.CharField(blank=True, max_length=200)),
                ('madrina', models.CharField(blank=True, max_length=200)),
                ('no_partida', models.CharField(max_length=50)),
                ('libro', models.CharField(max_length=50)),
                ('folio', models.CharField(max_length=50)),
                ('sacerdote', models.CharField(max_length=200)),
                ('nota', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['no_partida', 'libro', 'folio'],
            },
        ),
    ]
