# Generated by Django 5.0.2 on 2025-03-14 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comunion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_comunion', models.DateField()),
                ('libro', models.CharField(max_length=50)),
                ('folio', models.CharField(max_length=50)),
                ('partida', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.DateField()),
                ('nombre_padre', models.CharField(max_length=200)),
                ('nombre_madre', models.CharField(max_length=200)),
                ('nombre_padrino', models.CharField(max_length=200)),
                ('nombre_madrina', models.CharField(max_length=200)),
                ('ministro', models.CharField(max_length=200)),
                ('nota_marginal', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
