# Generated by Django 5.0.2 on 2025-03-14 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comuniones', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comunion',
            options={'ordering': ['-fecha_registro'], 'verbose_name': 'Comunión', 'verbose_name_plural': 'Comuniones'},
        ),
        migrations.RenameField(
            model_name='comunion',
            old_name='created_at',
            new_name='fecha_registro',
        ),
        migrations.RenameField(
            model_name='comunion',
            old_name='partida',
            new_name='no_partida',
        ),
        migrations.RenameField(
            model_name='comunion',
            old_name='ministro',
            new_name='nombre_comulgante',
        ),
        migrations.RenameField(
            model_name='comunion',
            old_name='nombre_madrina',
            new_name='sacerdote',
        ),
        migrations.RemoveField(
            model_name='comunion',
            name='nombre_padrino',
        ),
        migrations.RemoveField(
            model_name='comunion',
            name='nota_marginal',
        ),
        migrations.RemoveField(
            model_name='comunion',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='comunion',
            name='madrina',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='comunion',
            name='nota',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comunion',
            name='padrino',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='comunion',
            name='nombre_madre',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='comunion',
            name='nombre_padre',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
