# Generated by Django 5.0.2 on 2025-03-11 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bautismos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bautismo',
            name='noPartida',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='bautismo',
            name='nombre',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
