# Generated by Django 5.0.2 on 2025-03-11 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bautismos', '0002_alter_bautismo_nopartida_alter_bautismo_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bautismo',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
    ]
