# Generated by Django 5.0.2 on 2025-03-12 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bautismos', '0003_alter_bautismo_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bautismo',
            name='madrina',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bautismo',
            name='nombreMadre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bautismo',
            name='nombrePadre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bautismo',
            name='padrino',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
