# Generated by Django 5.0.2 on 2025-03-13 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bautismos', '0004_alter_bautismo_madrina_alter_bautismo_nombremadre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bautismo',
            name='estaCasado',
            field=models.BooleanField(default=False, verbose_name='¿Está casado por la iglesia?'),
        ),
        migrations.AddField(
            model_name='bautismo',
            name='nota',
            field=models.TextField(blank=True, null=True, verbose_name='Nota'),
        ),
    ]
