# Generated by Django 5.0.2 on 2025-03-14 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bautismos', '0006_alter_bautismo_estacasado_alter_bautismo_nota_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bautismo',
            name='fechaBautismo',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Bautismo'),
        ),
    ]
